start: The Block Shuffle game is beginning!
starterror: The game is already in progress!
stopgame: The Block Shuffle game has been ended!
stoperror: No Block Shuffle game running!
easy_materials:
  - ACACIA_BUTTON
  - ACACIA_DOOR
  - ACACIA_FENCE
  - ACACIA_FENCE_GATE
  - ACACIA_LEAVES
  - ACACIA_LOG
  - ACACIA_PLANKS
  - ACACIA_PRESSURE_PLATE
  - ACACIA_SAPLING
  - ACACIA_SIGN
  - ACACIA_SLAB
  - ACACIA_STAIRS
  - ACACIA_TRAPDOOR
  - ACACIA_WOOD
  - ALLIUM
  - ANDESITE
  - ANDESITE_SLAB
  - ANDESITE_STAIRS
  - ANDESITE_WALL
  - AZURE_BLUET
  - BARREL
  - BASALT
  - BEDROCK
  - BELL
  - BIRCH_BUTTON
  - BIRCH_DOOR
  - BIRCH_FENCE
  - BIRCH_FENCE_GATE
  - BIRCH_LEAVES
  - BIRCH_LOG
  - BIRCH_PLANKS
  - BIRCH_PRESSURE_PLATE
  - BIRCH_SAPLING
  - BIRCH_SIGN
  - BIRCH_SLAB
  - BIRCH_STAIRS
  - BIRCH_TRAPDOOR
  - BIRCH_WOOD
  - BLACK_BED
  - BLACK_CARPET
  - BLACK_STAINED_GLASS
  - BLACK_STAINED_GLASS_PANE
  - BLACK_WOOL
  - BLACKSTONE
  - BLACKSTONE_SLAB
  - BLACKSTONE_STAIRS
  - BLACKSTONE_WALL
  - BLUE_BED
  - BLUE_CARPET
  - BLUE_ORCHID
  - BLUE_STAINED_GLASS
  - BLUE_STAINED_GLASS_PANE
  - BLUE_WOOL
  - BONE_BLOCK
  - BROWN_MUSHROOM
  - BROWN_MUSHROOM_BLOCK
  - CACTUS
  - CAMPFIRE
  - CHEST
  - CHISELED_DEEPSLATE
  - CHISELED_SANDSTONE
  - COAL_ORE
  - COARSE_DIRT
  - COBBLED_DEEPSLATE
  - COBBLED_DEEPSLATE_SLAB
  - COBBLED_DEEPSLATE_STAIRS
  - COBBLED_DEEPSLATE_WALL
  - COBBLESTONE
  - COBBLESTONE_SLAB
  - COBBLESTONE_STAIRS
  - COBBLESTONE_WALL
  - COMPOSTER
  - COPPER_ORE
  - CORNFLOWER
  - CRAFTING_TABLE
  - CRIMSON_BUTTON
  - CRIMSON_DOOR
  - CRIMSON_FENCE
  - CRIMSON_FENCE_GATE
  - CRIMSON_FUNGUS
  - CRIMSON_HYPHAE
  - CRIMSON_NYLIUM
  - CRIMSON_PLANKS
  - CRIMSON_PRESSURE_PLATE
  - CRIMSON_SIGN
  - CRIMSON_SLAB
  - CRIMSON_STAIRS
  - CRIMSON_TRAPDOOR
  - CRYING_OBSIDIAN
  - CUT_SANDSTONE
  - CUT_SANDSTONE_SLAB
  - CYAN_BED
  - CYAN_CARPET
  - CYAN_STAINED_GLASS
  - CYAN_STAINED_GLASS_PANE
  - CYAN_WOOL
  - DANDELION
  - DARK_OAK_BUTTON
  - DARK_OAK_DOOR
  - DARK_OAK_FENCE
  - DARK_OAK_FENCE_GATE
  - DARK_OAK_LEAVES
  - DARK_OAK_LOG
  - DARK_OAK_PLANKS
  - DARK_OAK_PRESSURE_PLATE
  - DARK_OAK_SAPLING
  - DARK_OAK_SIGN
  - DARK_OAK_SLAB
  - DARK_OAK_STAIRS
  - DARK_OAK_TRAPDOOR
  - DARK_OAK_WOOD
  - DEAD_BUSH
  - DEEPSLATE
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_COPPER_ORE
  - DIORITE
  - DIORITE_SLAB
  - DIORITE_STAIRS
  - DIORITE_WALL
  - DIRT
  - DRIED_KELP_BLOCK
  - FERN
  - FLETCHING_TABLE
  - FLOWER_POT
  - FLOWERING_AZALEA
  - FLOWERING_AZALEA_LEAVES
  - FURNACE
  - GLASS
  - GLASS_PANE
  - GLOWSTONE
  - GOLD_ORE
  - GRANITE
  - GRANITE_SLAB
  - GRANITE_STAIRS
  - GRANITE_WALL
  - GRAVEL
  - GRAY_BED
  - GRAY_CARPET
  - GRAY_STAINED_GLASS
  - GRAY_STAINED_GLASS_PANE
  - GRAY_WOOL
  - GREEN_BED
  - GREEN_CARPET
  - GREEN_STAINED_GLASS
  - GREEN_STAINED_GLASS_PANE
  - GREEN_WOOL
  - HAY_BLOCK
  - JUNGLE_BUTTON
  - JUNGLE_DOOR
  - JUNGLE_FENCE
  - JUNGLE_FENCE_GATE
  - JUNGLE_LEAVES
  - JUNGLE_LOG
  - JUNGLE_PLANKS
  - JUNGLE_PRESSURE_PLATE
  - JUNGLE_SAPLING
  - JUNGLE_SIGN
  - JUNGLE_SLAB
  - JUNGLE_STAIRS
  - JUNGLE_TRAPDOOR
  - JUNGLE_WOOD
  - LANTERN
  - LAPIS_LAZULI
  - LAPIS_ORE
  - LARGE_FERN
  - LIGHT_BLUE_BED
  - LIGHT_BLUE_CARPET
  - LIGHT_BLUE_STAINED_GLASS
  - LIGHT_BLUE_STAINED_GLASS_PANE
  - LIGHT_BLUE_WOOL
  - LIGHT_GRAY_BED
  - LIGHT_GRAY_CARPET
  - LIGHT_GRAY_STAINED_GLASS
  - LIGHT_GRAY_STAINED_GLASS_PANE
  - LIGHT_GRAY_WOOL
  - LILAC
  - LILY_OF_THE_VALLEY
  - LILY_PAD
  - LOOM
  - MAGENTA_BED
  - MAGENTA_CARPET
  - MAGENTA_STAINED_GLASS
  - MAGENTA_STAINED_GLASS_PANE
  - MAGENTA_WOOL
  - MAGMA_BLOCK
  - MANGROVE_BUTTON
  - MANGROVE_DOOR
  - MANGROVE_FENCE
  - MANGROVE_FENCE_GATE
  - MANGROVE_LEAVES
  - MANGROVE_LOG
  - MANGROVE_PLANKS
  - MANGROVE_PRESSURE_PLATE
  - MANGROVE_ROOTS
  - MANGROVE_SIGN
  - MANGROVE_SLAB
  - MANGROVE_STAIRS
  - MANGROVE_TRAPDOOR
  - MANGROVE_WOOD
  - MELON
  - MUSHROOM_STEM
  - NETHER_QUARTZ_ORE
  - NETHER_SPROUTS
  - NETHER_WART
  - NETHER_WART_BLOCK
  - NETHERRACK
  - OAK_BUTTON
  - OAK_DOOR
  - OAK_FENCE
  - OAK_FENCE_GATE
  - OAK_LEAVES
  - OAK_LOG
  - OAK_PLANKS
  - OAK_PRESSURE_PLATE
  - OAK_SAPLING
  - OAK_SIGN
  - OAK_SLAB
  - OAK_STAIRS
  - OAK_TRAPDOOR
  - OAK_WOOD
  - OBSIDIAN
  - OXEYE_DAISY
  - PEONY
  - PINK_BED
  - PINK_CARPET
  - PINK_GLAZED_TERRACOTTA
  - PINK_STAINED_GLASS
  - PINK_STAINED_GLASS_PANE
  - PINK_TERRACOTTA
  - PINK_TULIP
  - PINK_WOOL
  - PODZOL
  - POPPY
  - POTTED_ACACIA_SAPLING
  - POTTED_ALLIUM
  - POTTED_AZALEA_BUSH
  - POTTED_AZURE_BLUET
  - POTTED_BAMBOO
  - POTTED_BIRCH_SAPLING
  - POTTED_BLUE_ORCHID
  - POTTED_BROWN_MUSHROOM
  - POTTED_CACTUS
  - POTTED_CORNFLOWER
  - POTTED_CRIMSON_FUNGUS
  - POTTED_CRIMSON_ROOTS
  - POTTED_DANDELION
  - POTTED_DARK_OAK_SAPLING
  - POTTED_DEAD_BUSH
  - POTTED_FERN
  - POTTED_FLOWERING_AZALEA_BUSH
  - POTTED_JUNGLE_SAPLING
  - POTTED_LILY_OF_THE_VALLEY
  - POTTED_MANGROVE_PROPAGULE
  - POTTED_OAK_SAPLING
  - POTTED_ORANGE_TULIP
  - POTTED_OXEYE_DAISY
  - POTTED_PINK_TULIP
  - POTTED_POPPY
  - POTTED_RED_MUSHROOM
  - POTTED_RED_TULIP
  - POTTED_SPRUCE_SAPLING
  - POTTED_WARPED_FUNGUS
  - POTTED_WARPED_ROOTS
  - POTTED_WHITE_TULIP
  - POWDER_SNOW
  - PUMPKIN
  - PURPLE_BED
  - PURPLE_CARPET
  - PURPLE_CONCRETE
  - PURPLE_CONCRETE_POWDER
  - PURPLE_GLAZED_TERRACOTTA
  - PURPLE_STAINED_GLASS
  - PURPLE_STAINED_GLASS_PANE
  - PURPLE_TERRACOTTA
  - PURPLE_WOOL
  - QUARTZ_BLOCK
  - QUARTZ_BRICKS
  - QUARTZ_SLAB
  - RAW_COPPER_BLOCK
  - RAW_GOLD_BLOCK
  - RAW_IRON_BLOCK
  - RED_BED
  - RED_CANDLE
  - RED_CONCRETE
  - RED_CONCRETE_POWDER
  - RED_GLAZED_TERRACOTTA
  - RED_STAINED_GLASS
  - RED_STAINED_GLASS_PANE
  - RED_TERRACOTTA
  - RED_TULIP
  - RED_WOOL
  - REDSTONE_ORE
  - ROOTED_DIRT
  - SAND
  - SANDSTONE
  - SANDSTONE_SLAB
  - SANDSTONE_STAIRS
  - SANDSTONE_WALL
  - SHROOMLIGHT
  - SMOKER
  - SMOOTH_SANDSTONE
  - SMOOTH_STONE
  - SNOW_BLOCK
  - SOUL_SAND
  - SOUL_SOIL
  - SPRUCE_BUTTON
  - SPRUCE_DOOR
  - SPRUCE_FENCE
  - SPRUCE_FENCE_GATE
  - SPRUCE_LEAVES
  - SPRUCE_LOG
  - SPRUCE_PLANKS
  - SPRUCE_PRESSURE_PLATE
  - SPRUCE_SAPLING
  - SPRUCE_SIGN
  - SPRUCE_SLAB
  - SPRUCE_STAIRS
  - SPRUCE_TRAPDOOR
  - SPRUCE_WOOD
  - STONE
  - STRIPPED_ACACIA_LOG
  - STRIPPED_ACACIA_WOOD
  - STRIPPED_BIRCH_LOG
  - STRIPPED_BIRCH_WOOD
  - STRIPPED_CRIMSON_HYPHAE
  - STRIPPED_CRIMSON_STEM
  - STRIPPED_DARK_OAK_LOG
  - STRIPPED_DARK_OAK_WOOD
  - STRIPPED_JUNGLE_LOG
  - STRIPPED_JUNGLE_WOOD
  - STRIPPED_MANGROVE_LOG
  - STRIPPED_MANGROVE_WOOD
  - STRIPPED_OAK_LOG
  - STRIPPED_OAK_WOOD
  - STRIPPED_SPRUCE_LOG
  - STRIPPED_SPRUCE_WOOD
  - STRIPPED_WARPED_HYPHAE
  - STRIPPED_WARPED_STEM
  - SUNFLOWER
  - SWEET_BERRY_BUSH
  - TERRACOTTA
  - TINTED_GLASS
  - TUFF
  - TWISTING_VINES
  - TWISTING_VINES_PLANT
  - VINE
  - WARPED_BUTTON
  - WARPED_DOOR
  - WARPED_FENCE
  - WARPED_FENCE_GATE
  - WARPED_HYPHAE
  - WARPED_NYLIUM
  - WARPED_PLANKS
  - WARPED_PRESSURE_PLATE
  - WARPED_ROOTS
  - WARPED_SIGN
  - WARPED_SLAB
  - WARPED_STAIRS
  - WARPED_STEM
  - WARPED_TRAPDOOR
  - WARPED_WART_BLOCK
  - WATER
  - WEEPING_VINES
  - WEEPING_VINES_PLANT
  - WHITE_BED
  - WHITE_CARPET
  - WHITE_CONCRETE
  - WHITE_CONCRETE_POWDER
  - WHITE_GLAZED_TERRACOTTA
  - WHITE_STAINED_GLASS
  - WHITE_STAINED_GLASS_PANE
  - WHITE_TERRACOTTA
  - WHITE_TULIP
  - WHITE_WOOL
  - YELLOW_BED
  - YELLOW_CARPET
  - YELLOW_CONCRETE
  - YELLOW_CONCRETE_POWDER
  - YELLOW_GLAZED_TERRACOTTA
  - YELLOW_STAINED_GLASS
  - YELLOW_STAINED_GLASS_PANE
  - YELLOW_TERRACOTTA
  - YELLOW_WOOL
hard_materials:
  - ACTIVATOR_RAIL
  - AMETHYST_BLOCK
  - AMETHYST_CLUSTER
  - ANCIENT_DEBRIS
  - ANVIL
  - BEEHIVE
  - BIG_DRIPLEAF
  - BLACK_CANDLE
  - BLACK_CONCRETE
  - BLACK_CONCRETE_POWDER
  - BLACK_GLAZED_TERRACOTTA
  - BLACK_TERRACOTTA
  - BLAST_FURNACE
  - BLAZE_POWDER
  - BLAZE_ROD
  - BLUE_CANDLE
  - BLUE_CONCRETE
  - BLUE_CONCRETE_POWDER
  - BLUE_GLAZED_TERRACOTTA
  - BLUE_ICE
  - BLUE_TERRACOTTA
  - BOOKSHELF
  - BRAIN_CORAL
  - BRAIN_CORAL_BLOCK
  - BRAIN_CORAL_FAN
  - BRICK_SLAB
  - BRICK_STAIRS
  - BRICK_WALL
  - BROWN_BED
  - BROWN_CANDLE
  - BROWN_CARPET
  - BROWN_CONCRETE
  - BROWN_CONCRETE_POWDER
  - BROWN_GLAZED_TERRACOTTA
  - BROWN_STAINED_GLASS
  - BROWN_STAINED_GLASS_PANE
  - BROWN_TERRACOTTA
  - BROWN_WOOL
  - BUBBLE_CORAL
  - BUBBLE_CORAL_BLOCK
  - BUBBLE_CORAL_FAN
  - BUDDING_AMETHYST
  - CAKE
  - CALCITE
  - CANDLE
  - CARTOGRAPHY_TABLE
  - CARVED_PUMPKIN
  - CAULDRON
  - CHISELED_NETHER_BRICKS
  - CHISELED_POLISHED_BLACKSTONE
  - CHISELED_QUARTZ_BLOCK
  - CHISELED_STONE_BRICKS
  - COBWEB
  - COMPARATOR
  - COPPER_BLOCK
  - CYAN_CANDLE
  - CYAN_CONCRETE
  - CYAN_CONCRETE_POWDER
  - CYAN_GLAZED_TERRACOTTA
  - CYAN_TERRACOTTA
  - DARK_PRISMARINE
  - DARK_PRISMARINE_SLAB
  - DARK_PRISMARINE_STAIRS
  - DEAD_BRAIN_CORAL
  - DEAD_BRAIN_CORAL_BLOCK
  - DEAD_BUBBLE_CORAL
  - DEAD_BUBBLE_CORAL_BLOCK
  - DEAD_BUBBLE_CORAL_FAN
  - DEAD_FIRE_CORAL
  - DEAD_FIRE_CORAL_BLOCK
  - DEAD_FIRE_CORAL_FAN
  - DEAD_HORN_CORAL
  - DEAD_HORN_CORAL_BLOCK
  - DEAD_HORN_CORAL_FAN
  - DEAD_TUBE_CORAL
  - DEAD_TUBE_CORAL_BLOCK
  - DEAD_TUBE_CORAL_FAN
  - DEEPSLATE_BRICK_SLAB
  - DEEPSLATE_BRICK_STAIRS
  - DEEPSLATE_BRICK_WALL
  - DEEPSLATE_BRICKS
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_EMERALD_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_TILE_SLAB
  - DEEPSLATE_TILE_STAIRS
  - DEEPSLATE_TILE_WALL
  - DEEPSLATE_TILES
  - DETECTOR_RAIL
  - DIAMOND_BLOCK
  - DIAMOND_ORE
  - DISPENSER
  - DRIPSTONE_BLOCK
  - DROPPER
  - EMERALD_BLOCK
  - EMERALD_ORE
  - END_PORTAL_FRAME
  - FIRE_CORAL
  - FIRE_CORAL_BLOCK
  - FIRE_CORAL_FAN
  - GILDED_BLACKSTONE
  - GOLD_BLOCK
  - GRAY_CANDLE
  - GRAY_CONCRETE
  - GRAY_CONCRETE_POWDER
  - GRAY_GLAZED_TERRACOTTA
  - GRAY_TERRACOTTA
  - GREEN_CANDLE
  - GREEN_CONCRETE
  - GREEN_CONCRETE_POWDER
  - GREEN_GLAZED_TERRACOTTA
  - GREEN_TERRACOTTA
  - GRINDSTONE
  - HEAVY_WEIGHTED_PRESSURE_PLATE
  - HONEY_BLOCK
  - HOPPER
  - HORN_CORAL
  - HORN_CORAL_BLOCK
  - HORN_CORAL_FAN
  - ICE
  - IRON_BARS
  - IRON_BLOCK
  - IRON_DOOR
  - IRON_ORE
  - IRON_TRAPDOOR
  - JACK_O_LANTERN
  - JUKEBOX
  - LAPIS_BLOCK
  - LARGE_AMETHYST_BUD
  - LECTERN
  - LEVER
  - LIGHT_BLUE_CANDLE
  - LIGHT_BLUE_CONCRETE
  - LIGHT_BLUE_CONCRETE_POWDER
  - LIGHT_BLUE_GLAZED_TERRACOTTA
  - LIGHT_BLUE_TERRACOTTA
  - LIGHT_GRAY_CANDLE
  - LIGHT_GRAY_CONCRETE
  - LIGHT_GRAY_CONCRETE_POWDER
  - LIGHT_GRAY_GLAZED_TERRACOTTA
  - LIGHT_GRAY_TERRACOTTA
  - LIGHT_WEIGHTED_PRESSURE_PLATE
  - LIGHTNING_ROD
  - LIME_BED
  - LIME_CANDLE
  - LIME_CARPET
  - LIME_CONCRETE
  - LIME_CONCRETE_POWDER
  - LIME_GLAZED_TERRACOTTA
  - LIME_STAINED_GLASS
  - LIME_STAINED_GLASS_PANE
  - LIME_TERRACOTTA
  - LIME_WOOL
  - MAGENTA_CANDLE
  - MAGENTA_CONCRETE
  - MAGENTA_CONCRETE_POWDER
  - MAGENTA_GLAZED_TERRACOTTA
  - MAGENTA_TERRACOTTA
  - MEDIUM_AMETHYST_BUD
  - MOSS_BLOCK
  - MOSS_CARPET
  - MOSSY_COBBLESTONE
  - MOSSY_COBBLESTONE_SLAB
  - MOSSY_COBBLESTONE_STAIRS
  - MOSSY_COBBLESTONE_WALL
  - MOSSY_STONE_BRICK_SLAB
  - MOSSY_STONE_BRICK_STAIRS
  - MOSSY_STONE_BRICK_WALL
  - MOSSY_STONE_BRICKS
  - MUD
  - MUD_BRICK_SLAB
  - MUD_BRICK_STAIRS
  - MUD_BRICK_WALL
  - MUD_BRICKS
  - MUDDY_MANGROVE_ROOTS
  - MYCELIUM
  - NETHER_BRICK_FENCE
  - NETHER_BRICK_SLAB
  - NETHER_BRICK_STAIRS
  - NETHER_BRICK_WALL
  - NETHER_BRICKS
  - NETHER_GOLD_ORE
  - OBSERVER
  - ORANGE_BED
  - ORANGE_CANDLE
  - ORANGE_CARPET
  - ORANGE_CONCRETE
  - ORANGE_CONCRETE_POWDER
  - ORANGE_GLAZED_TERRACOTTA
  - ORANGE_STAINED_GLASS
  - ORANGE_STAINED_GLASS_PANE
  - ORANGE_TERRACOTTA
  - ORANGE_TULIP
  - ORANGE_WOOL
  - PINK_CANDLE
  - PINK_CONCRETE
  - PINK_CONCRETE_POWDER
  - POINTED_DRIPSTONE
  - POWERED_RAIL
  - PRISMARINE_BRICK_SLAB
  - PRISMARINE_BRICK_STAIRS
  - PRISMARINE_BRICKS
  - PRISMARINE_SLAB
  - PRISMARINE_STAIRS
  - PURPLE_CANDLE
  - QUARTZ_PILLAR
  - QUARTZ_STAIRS
  - RAIL
  - RED_CARPET
  - RED_MUSHROOM
  - RED_MUSHROOM_BLOCK
  - RED_NETHER_BRICK_SLAB
  - RED_NETHER_BRICK_STAIRS
  - RED_NETHER_BRICK_WALL
  - RED_NETHER_BRICKS
  - REDSTONE_BLOCK
  - REPEATER
  - SCAFFOLDING
  - SLIME_BLOCK
  - SMALL_AMETHYST_BUD
  - SMALL_DRIPLEAF
  - SMITHING_TABLE
  - SMOOTH_BASALT
  - SMOOTH_QUARTZ
  - SMOOTH_QUARTZ_SLAB
  - SMOOTH_QUARTZ_STAIRS
  - SMOOTH_SANDSTONE_SLAB
  - SMOOTH_SANDSTONE_STAIRS
  - SMOOTH_STONE_SLAB
  - SOUL_CAMPFIRE
  - SOUL_LANTERN
  - STONE_BRICK_SLAB
  - STONE_BRICK_STAIRS
  - STONE_BRICK_WALL
  - STONE_BRICKS
  - STONE_BUTTON
  - STONE_PRESSURE_PLATE
  - STONE_SLAB
  - STONE_STAIRS
  - STONECUTTER
  - TNT
  - TUBE_CORAL
  - TUBE_CORAL_BLOCK
  - TUBE_CORAL_FAN
  - WATER_CAULDRON
  - WAXED_COPPER_BLOCK
  - WAXED_CUT_COPPER
  - WAXED_CUT_COPPER_SLAB
  - WAXED_CUT_COPPER_STAIRS
  - WHITE_CANDLE
  - YELLOW_CANDLE